#!/bin/bash

echo "🚀 Portal Monemusic 수동 배포 가이드"
echo "========================================"
echo ""
echo "1. 서버 접속:"
echo "   ssh -i ~/monemusic root@115.68.195.125"
echo ""
echo "2. 프로젝트 디렉토리로 이동 (없으면 clone):"
echo "   # 디렉토리가 있는지 확인"
echo "   ls /root/portal-monemusic"
echo "   "
echo "   # 없으면 clone"
echo "   cd /root"
echo "   git clone https://github.com/devchohwan/portal_monemusic.git portal-monemusic"
echo "   "
echo "   # 있으면 pull"
echo "   cd /root/portal-monemusic"
echo "   git pull origin main"
echo ""
echo "3. Docker 이미지 빌드:"
echo "   docker build -t amuguona/portal-monemusic:manual-fix ."
echo ""
echo "4. Docker Hub에 푸시 (선택사항):"
echo "   docker push amuguona/portal-monemusic:manual-fix"
echo ""
echo "5. 기존 컨테이너 중지 및 삭제:"
echo "   docker stop portal-monemusic-manual"
echo "   docker rm portal-monemusic-manual"
echo ""
echo "6. 새 컨테이너 실행:"
echo "   docker run -d \\"
echo "     --name portal-monemusic-manual \\"
echo "     --network kamal \\"
echo "     -v portal_monemusic_storage:/rails/storage \\"
echo "     -e RAILS_MASTER_KEY=d852cbb93057373a82518521ec2e24a0 \\"
echo "     -e RAILS_ENV=production \\"
echo "     -e SOLAPI_API_KEY=your_api_key \\"
echo "     -e SOLAPI_API_SECRET=your_api_secret \\"
echo "     -e SOLAPI_SENDER=발신번호 \\"
echo "     --entrypoint '' \\"
echo "     amuguona/portal-monemusic:manual-fix \\"
echo "     ./bin/thrust ./bin/rails server"
echo ""
echo "7. 데이터베이스 마이그레이션 실행:"
echo "   docker exec portal-monemusic-manual /rails/bin/rails db:migrate RAILS_ENV=production"
echo ""
echo "8. 컨테이너 상태 확인:"
echo "   docker ps | grep portal-monemusic-manual"
echo ""
echo "9. 로그 확인:"
echo "   docker logs -f portal-monemusic-manual --tail 50"
echo ""
echo "========================================"
echo "✅ 배포 완료 후 확인: https://portal.monemusic.com"