version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: staging-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: monemusic_staging
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: monemusic_staging
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build: .
    container_name: staging-portal-web
    ports:
      - "3010:80"
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true"
      SERVICE_TYPE: portal
      DB_HOST: postgres
      DB_PORT: 5432
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SOLAPI_API_KEY: ${SOLAPI_API_KEY}
      SOLAPI_API_SECRET: ${SOLAPI_API_SECRET}
      SOLAPI_SENDER_PHONE: ${SOLAPI_SENDER_PHONE}
    depends_on:
      - postgres
    volumes:
      - staging_portal_storage:/rails/storage
    restart: unless-stopped

  practice:
    build: .
    container_name: staging-practice-web
    ports:
      - "3011:80"
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true"
      SERVICE_TYPE: practice
      DB_HOST: postgres
      DB_PORT: 5432
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SOLAPI_API_KEY: ${SOLAPI_API_KEY}
      SOLAPI_API_SECRET: ${SOLAPI_API_SECRET}
      SOLAPI_SENDER_PHONE: ${SOLAPI_SENDER_PHONE}
    depends_on:
      - postgres
    volumes:
      - staging_practice_storage:/rails/storage
    restart: unless-stopped

  makeup:
    build: .
    container_name: staging-makeup-web
    ports:
      - "3012:80"
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true"
      SERVICE_TYPE: makeup
      DB_HOST: postgres
      DB_PORT: 5432
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SOLAPI_API_KEY: ${SOLAPI_API_KEY}
      SOLAPI_API_SECRET: ${SOLAPI_API_SECRET}
      SOLAPI_SENDER_PHONE: ${SOLAPI_SENDER_PHONE}
    depends_on:
      - postgres
    volumes:
      - staging_makeup_storage:/rails/storage
    restart: unless-stopped

volumes:
  postgres_staging_data:
  staging_portal_storage:
  staging_practice_storage:
  staging_makeup_storage:
