# PostgreSQL configuration
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: portal_monemusic
    username: <%= ENV.fetch("DB_USERNAME", "monemusic") %>
    password: <%= ENV.fetch("DB_PASSWORD", "5dnjfdjr1!") %>
    host: <%= ENV.fetch("DB_HOST", "localhost") %>
    port: <%= ENV.fetch("DB_PORT", 5432) %>

test:
  <<: *default
  database: monemusic_test
  username: <%= ENV.fetch("DB_USERNAME", "monemusic") %>
  password: <%= ENV.fetch("DB_PASSWORD", "monemusic2024!") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

production:
  primary:
    <<: *default
    database: monemusic_production
    username: <%= ENV.fetch("DB_USERNAME", "monemusic") %>
    password: <%= ENV.fetch("DB_PASSWORD", "monemusic2024!") %>
    host: <%= ENV.fetch("DB_HOST", "115.68.195.125") %>
    port: <%= ENV.fetch("DB_PORT", 5432) %>
  cache:
    <<: *default
    database: monemusic_production_cache
    username: <%= ENV.fetch("DB_USERNAME", "monemusic") %>
    password: <%= ENV.fetch("DB_PASSWORD", "monemusic2024!") %>
    host: <%= ENV.fetch("DB_HOST", "115.68.195.125") %>
    port: <%= ENV.fetch("DB_PORT", 5432) %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: monemusic_production_queue
    username: <%= ENV.fetch("DB_USERNAME", "monemusic") %>
    password: <%= ENV.fetch("DB_PASSWORD", "monemusic2024!") %>
    host: <%= ENV.fetch("DB_HOST", "115.68.195.125") %>
    port: <%= ENV.fetch("DB_PORT", 5432) %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: monemusic_production_cable
    username: <%= ENV.fetch("DB_USERNAME", "monemusic") %>
    password: <%= ENV.fetch("DB_PASSWORD", "monemusic2024!") %>
    host: <%= ENV.fetch("DB_HOST", "115.68.195.125") %>
    port: <%= ENV.fetch("DB_PORT", 5432) %>
    migrations_paths: db/cable_migrate